# v2 Syntax
version: '2'
# Named Volumes
volumes:
  # Postgres Data
  sandbox-postgres-data:
    driver: local
  # MySQL Data
  sandbox-mysql-data:
    driver: local
services:
  # Web+PHP (ZendServer)
  zend:
    container_name: project-zendserver
    build:
      context: ./
      dockerfile: ./php-zendserver/9.1/dockerfile
    ports:
      - "80:80"
      - "10081:10081"
    volumes:
      - ./www:/var/www
    environment:
      - ZS_ADMIN_PASSWORD=admin
  # Postgres
  postgres:
    container_name: project-db-postgres
    build:
      context: ./
      dockerfile: ./postgres/9.6/dockerfile
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
  # MySQL
  mysql:
    container_name: project-db-mysql
    build:
      context: ./
      dockerfile: ./mysql/5.7/dockerfile
    volumes:
      - sandbox-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_USER_=sandbox
      - MYSQL_PASSWORD=sandbox
