# v2 Syntax
version: '2'
# Named Volumes
volumes:
  # Postgres Data
  sandbox-postgres-data:
    driver: local
  # MySQL Data
  sandbox-mysql-data:
    driver: local
services:
  # Web (Nginx)
  web:
    container_name: project-web
    build:
      context: ./
      dockerfile: ./nginx/1.13/dockerfile
    volumes:
      - ./../www:/var/www
    ports:
      - "80:80"
    links:
      - app
  # PHP (FPM)
  app:
    container_name: project-app
    build:
      context: ./
      dockerfile: ./php/7.2-fpm/dockerfile
    volumes:
      - ./../www:/var/www
    links:
      - postgres
      - mysql
  # Postgres
  postgres:
    container_name: project-db-postgres
    image: "postgres:9.6"
    volumes:
      - sandbox-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sandbox
      - POSTGRES_USER=sandbox
  # MySQL
  mysql:
    container_name: project-db-mysql
    image: "mysql:5.7"
    volumes:
      - sandbox-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_USER_=sandbox
      - MYSQL_PASSWORD=sandbox
