version: "3.7"
services:

  #PHP-FPM (7.4)
  php74:
    build: container-build/php/7.4-fpm
    container_name: project-php74
    working_dir: /var/www
    ports:
      - "9000:9000"
    tty: true
    volumes:
      - ./www:/var/www

  #NGINX
  nginx:
    image: nginx:1.13
    container_name: project-ngnix
    working_dir: /var/www
    volumes:
      - ./vhosts:/etc/nginx/conf.d
      - ./www:/var/www
      - ./logs:/etc/nginx/logs
    ports:
      - "80:80"
      